"""add catalog inventory reservations loans notifications

Revision ID: f49eabedfcc9
Revises: d6b28cc78b41
Create Date: 2026-02-17 11:26:02.175577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f49eabedfcc9'
down_revision: Union[str, Sequence[str], None] = 'd6b28cc78b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors'))
    )
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('isbn', name='uq_books_isbn')
    )
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('code', name=op.f('uq_locations_code'))
    )
    op.create_table('publishers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishers')),
    sa.UniqueConstraint('name', name=op.f('uq_publishers_name'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('book_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.UUID(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('draft','pending','published','archived')", name=op.f('ck_book_cards_status')),
    sa.CheckConstraint('publish_year IS NULL OR (publish_year >= 0 AND publish_year <= 3000)', name=op.f('ck_book_cards_publish_year_range')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_cards_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_book_cards_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], name=op.f('fk_book_cards_publisher_id_publishers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_book_cards_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_cards'))
    )
    op.create_table('book_copies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('inventory_code', sa.Text(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("condition IN ('new','good','ok','bad')", name=op.f('ck_book_copies_condition')),
    sa.CheckConstraint("status IN ('available','reserved','issued','lost','repair','archived')", name=op.f('ck_book_copies_status')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_copies_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_book_copies_location_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_copies')),
    sa.UniqueConstraint('inventory_code', name='uq_book_copies_inventory_code'),
    sa.UniqueConstraint('inventory_code', name=op.f('uq_book_copies_inventory_code'))
    )
    op.create_table('book_similarities',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('similar_book_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('book_id <> similar_book_id', name=op.f('ck_book_similarities_not_self')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_book_similarities_score_range')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_similarities_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_book_id'], ['books.id'], name=op.f('fk_book_similarities_similar_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'similar_book_id', name=op.f('pk_book_similarities'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('book_card_authors',
    sa.Column('book_card_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_book_card_authors_author_id_authors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_card_id'], ['book_cards.id'], name=op.f('fk_book_card_authors_book_card_id_book_cards'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_card_id', 'author_id', name=op.f('pk_book_card_authors'))
    )
    op.create_table('book_card_genres',
    sa.Column('book_card_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['book_card_id'], ['book_cards.id'], name=op.f('fk_book_card_genres_book_card_id_book_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_card_genres_genre_id_genres'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('book_card_id', 'genre_id', name=op.f('pk_book_card_genres'))
    )
    op.create_table('book_current_card',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('published_card_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_current_card_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_card_id'], ['book_cards.id'], name=op.f('fk_book_current_card_published_card_id_book_cards'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('book_id', name=op.f('pk_book_current_card')),
    sa.UniqueConstraint('published_card_id', name=op.f('uq_book_current_card_published_card_id'))
    )
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('copy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('requested','approved','rejected','cancelled','expired','fulfilled')", name=op.f('ck_reservations_status')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reservations_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], name=op.f('fk_reservations_copy_id_book_copies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_reservations_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('copy_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('open','closed','overdue')", name=op.f('ck_loans_status')),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], name=op.f('fk_loans_copy_id_book_copies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_loans_issued_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_loans_received_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_loans_reservation_id_reservations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('reservations')
    op.drop_table('book_current_card')
    op.drop_table('book_card_genres')
    op.drop_table('book_card_authors')
    op.drop_table('notifications')
    op.drop_table('book_similarities')
    op.drop_table('book_copies')
    op.drop_table('book_cards')
    op.drop_table('audit_log')
    op.drop_table('publishers')
    op.drop_table('locations')
    op.drop_table('genres')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
